spring:
    application:
        name: spring-boot-completablefuture

    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: SpringBootCompletableFuture

application:
    async:
        core-pool-size: 10
        max-pool-size: 50
        queue-capacity: 10000